spring:
  redis:
    database: 0  #Redis数据库索引（默认为0）
    host: 192.168.0.1
    password: 123
    lettuce:
      pool:
        max-active: 20 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 5 #连接池中的最大空闲连接
        max-wait: -1 #连接池最大连接数（使用负值表示没有限制）
        min-idle: 0 #连接池中的最小空闲连接
    port: 6379
    timeout: 1800000 #连接超时时间（毫秒）
